version: "3"

services:
  re-characters-service:
    container_name: re-characters-service
    image: ${re.characters.service.image.name}:${re.characters.service.image.version}
    ports:
      - "8000:8000"
    volumes:
      - ${project.build.directory}/spring-custom-config/re-rest-application.yaml:/config/application.yaml
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "app.jar","--spring.config.location=file:/config/application.yaml"]
    depends_on:
      - re-active-mq
      - re-characters-database

  re-active-mq:
    container_name: re-queue
    image: ${re.active.mq.image.name}:${re.active.mq.image.version}
    ports:
      - "61616:61616"
      - "8161:8161"

  re-characters-database:
    container_name: re-characters-database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/re-characters-database:/var/lib/postgresql/data
      - ${project.build.directory}/db-init-scripts:/docker-entrypoint-initdb.d

